# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 1

environment:
  matrix:
  - emacs: 24
  - emacs: 25

install:
  - ps: switch($env:emacs){ 24 {choco install emacs --no-progress} 25 {choco install emacs64 --no-progress} default {throw "Emacs install fail"}}
  - choco install ghc --no-progress
  - choco install haskell-stack --no-progress
  - refreshenv

build_script:
  - C:\msys64\usr\bin\bash -l -c "cd ${APPVEYOR_BUILD_FOLDER} && make"

test_script:
  - C:\msys64\usr\bin\bash -l -c "cd ${APPVEYOR_BUILD_FOLDER} && make check"
