build:
  image: ensime/ensime:v1.x-cache
  pull: true
  commands:
    - git log | head -n 20 ;
    - host `curl -s http://httpbin.org/ip | jq -r '.origin'` || true ;
    - cask pkg-file ;
      cask install ;
      cask build ;
    - cask exec ert-runner ;
    - cask exec ecukes ;
    - test/run_emacs_tests.sh ;
      if [ -n "$UNDERCOVER" ] && [ -f "coveralls.json" ] ; then
        curl -v -include --form json_file=@coveralls.json https://coveralls.io/api/v1/jobs || true ;
      fi

matrix:
  EMACS:
    - /opt/emacs-24.5/bin/emacs
    - /opt/emacs-24.3/bin/emacs
