language: generic
sudo: required

services:
  - docker

env:
  matrix:
    - TARGET=emacs24
    - TARGET=emacs-snapshot
    - TARGET=emacs25
    - TARGET=deploy-manual
    - TARGET=check-external
  global:
    - secure: "ejv1+ub/v+Hm/23fhp4zLAHT3HiCG+YdDHai57LDe4LfEZCeGz4i/6LazbPbwm58v2YuKvMcdNshebc1s4A293ARJryPyFfW/8kEe+3hQ+cDxunNdHfqcS8SyhcDG0mrv7dqiVAtMJqB8qZb0c161KeEM8nyhC0wyQ+EZ5qJnzM="

matrix:
  allow_failures:
    - env: TARGET=emacs-snapshot
    - env: TARGET=check-external

install: |
    case "$TARGET" in
      emacs24)
        docker build -t haskell-mode-24 ./emacs-24 &&
        docker create --name haskell-mode-24 haskell-mode-24 &&
        docker cp $PWD haskell-mode-24:/root;
        ;;
      emacs25)
        docker build -t haskell-mode-25 ./emacs-25 &&
        docker create --name haskell-mode-25 haskell-mode-25 &&
        docker cp $PWD haskell-mode-25:/root;
        ;;
      emacs-snapshot)
        docker build -t haskell-mode-snapshot ./emacs-snapshot &&
        docker create --name haskell-mode-snapshot haskell-mode-snapshot &&
        docker cp $PWD haskell-mode-snapshot:/root;
        ;;
      deploy-manual)
        sudo apt-get update &&
        sudo apt-get install --no-install-suggests --no-install-recommends --force-yes texinfo emacs24-nox;
        ;;
      check-external)
        sudo add-apt-repository -y ppa:andreas-h/emacs &&
        sudo apt-get update &&
        sudo apt-get install --no-install-suggests --no-install-recommends --force-yes emacs24;
        ;;
      *)
    esac

script: |
    case "$TARGET" in
      emacs24)
        docker start -i haskell-mode-24;
        ;;
      emacs25)
        docker start -i haskell-mode-25;
        ;;
      emacs-snapshot)
        docker start -i haskell-mode-snapshot;
        ;;
      deploy-manual)
        EMACS=emacs24 make deploy-manual;
        ;;
      check-external)
        EMACS=emacs24 make check-external;
        ;;
      *)
    esac


notifications:
  email: false
  irc: "irc.freenode.org#haskell-emacs"

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
