language: emacs-lisp

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot

env:
  - EMACS_VERSION=24.4
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25.1
  - EMACS_VERSION=snapshot

before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask

install:
  - cask install

script:
  - cask exec ert-runner

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b1163bae60c65660fbd2
    on_success: change
    on_failure: always
    on_start: never
